package com.jynx.pro.blockchain.constant;

public enum TendermintTransaction {
    CREATE_ORDER,
    CANCEL_ORDER,
    AMEND_ORDER,
    CREATE_ORDER_MANY, // TODO
    CANCEL_ORDER_MANY, // TODO
    AMEND_ORDER_MANY, // TODO
    ADD_MARKET,
    AMEND_MARKET,
    SUSPEND_MARKET,
    UNSUSPEND_MARKET,
    ADD_ASSET,
    SUSPEND_ASSET,
    UNSUSPEND_ASSET,
    CREATE_WITHDRAWAL,
    CANCEL_WITHDRAWAL,
    CAST_VOTE,
    UPDATE_DELEGATION, // TODO
    CONFIRM_ETHEREUM_EVENTS,
    SETTLE_MARKETS,
    SYNC_PROPOSALS,
    UNKNOWN
}