package com.jynx.pro.constant;

public enum TendermintTransaction {
    CREATE_ORDER,
    CANCEL_ORDER,
    AMEND_ORDER,
    CREATE_ORDER_MANY,
    CANCEL_ORDER_MANY,
    AMEND_ORDER_MANY,
    ADD_MARKET,
    AMEND_MARKET,
    SUSPEND_MARKET,
    UNSUSPEND_MARKET,
    ADD_ASSET,
    SUSPEND_ASSET,
    UNSUSPEND_ASSET,
    CREATE_WITHDRAWAL,
    CANCEL_WITHDRAWAL,
    CAST_VOTE,
    UPDATE_DELEGATION, // TODO
    ADD_STAKE,
    REMOVE_STAKE,
    DEPOSIT_ASSET,
    SIGN_WITHDRAWAL_BATCHES, // TODO
    BATCH_WITHDRAWALS, // TODO
    DEBIT_WITHDRAWALS, // TODO
    CONFIRM_ETHEREUM_EVENTS,
    SETTLE_MARKETS,
    SYNC_PROPOSALS,
    UNKNOWN
}