package com.jynx.pro.constant;

public enum TendermintTransaction {
    CREATE_ORDER,
    CANCEL_ORDER,
    AMEND_ORDER,
    CREATE_ORDER_MANY,
    CANCEL_ORDER_MANY,
    AMEND_ORDER_MANY,
    ADD_MARKET,
    AMEND_MARKET,
    SUSPEND_MARKET,
    UNSUSPEND_MARKET,
    ADD_ASSET,
    SUSPEND_ASSET,
    UNSUSPEND_ASSET,
    CREATE_WITHDRAWAL,
    CANCEL_WITHDRAWAL,
    CAST_VOTE,
    VALIDATOR_APPLICATION, // TODO
    VALIDATOR_RESIGNATION, // TODO
    ADD_DELEGATION,
    REMOVE_DELEGATION,
    MONITOR_AUCTIONS,
    ADD_STAKE,
    REMOVE_STAKE,
    DEPOSIT_ASSET,
    SIGN_BRIDGE_UPDATES,
    EXECUTE_BRIDGE_UPDATES,
    SIGN_WITHDRAWAL_BATCHES,
    BATCH_WITHDRAWALS,
    DEBIT_WITHDRAWALS,
    CONFIRM_ETHEREUM_EVENTS,
    SETTLE_MARKETS,
    SYNC_PROPOSALS,
    UNKNOWN
}